### ISSUE TITLE
report.sh: 75: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by Nostang3** [dak180/FreeNAS-Report#15]
I downloaded the file on TrueNAS-13.0-U1.1 but when I run it throws a syntax error. I haven't altered the file in anyway. Running the script as root.

**Comment by dak180** [comment]
@Nostang3 please post (in code tags) your config file. I ask because I am running 13.0-U1.1 and have no such errors.

**Comment by Nostang3** [comment]
> @Nostang3 please post (in code tags) your config file. I ask because I am running 13.0-U1.1 and have no such errors.

It doesn't create a config file. I can't get it to run once to create it. At least that is what the directions say to do, run the script once to generate file then edit it and run again.

**Comment by dak180** [comment]
@Nostang3 What is the exact invocation line you are using for the script?

**Comment by Nostang3** [comment]
@dak180 `sh report.sh`

**Comment by Nostang3** [comment]
So maybe I'm just a noob or an idiot but I figured out it can run by doing `./report.sh`. I didn't know this. I've always ran .sh scripts by using sh invocation. Once I did that it runs fine now. Thanks for the replies and sorry if I wasted any of your time.
