### ISSUE TITLE
Wrong info in ZPool Status Report Summary

### ISSUE THREAD

**Issue by mkninc** [dak180/FreeNAS-Report#16]
Parsing of resilvering status info seems to have a problem. 

<img width="1085" alt="zpool report scrub info" src="https://user-images.githubusercontent.com/1223403/211367862-48e724cd-95fc-4e94-bb44-00f56b4af234.png">

Output from `zpool status`
```
pool: pool1
state: ONLINE
scan: resilvered 2.31T in 1 days 02:55:32 with 0 errors on Sat Dec 24 02:33:08 2022
config:
```

**Comment by dak180** [comment]
Can you give me the output of `zpool version` please @mkninc ?

**Comment by mkninc** [comment]
System is TrueNAS-12.0-U8 

```
 # zpool version
zfs-2.0.7-1
zfs-kmod-v2022012000-zfs_e870bd8cf
```

**Comment by dak180** [comment]
@mkninc if you can make a pull request with additional [examples](/dak180/FreeNAS-Report/commit/9e0be21) and also update the previous example you gave with the full output that would be very helpful. It is things like this that really make me wish there was an easy way to get this info in a json format.
