### ISSUE TITLE
Please Edit Config File

### ISSUE THREAD

**Issue by seniorm0ment** [dak180/FreeNAS-Report#18]
"/root/bin/report-generator/report.conf: line 4: $'\032': command not found
Please edit the config file for your setup"

Is the email I get when running on TrueNAS Core.
I edited in my email, and changed defaultFile to a 0. 

Edit: I figured this out. I had to then go into the config file and set defaultFile to 0, not the script.

However, I can't seem to get colors to show in email. Would colors show in plaintext email, or only if using html?

**Comment by dak180** [comment]
Colours are only in html.
