### ISSUE TITLE
Will this script be made compatible with TrueNAS SCALE?

### ISSUE THREAD

**Issue by Mannekino** [dak180/FreeNAS-Report#19]
Hi,

Are there plans to make a TrueNAS SCALE version of this script?

Thank you!

Kind regards,

Mannekino

**Comment by dak180** [comment]
Duplicate of #5. 

See [#6](https://github.com/dak180/FreeNAS-Report/pull/6#issuecomment-1422618352) for details on (an unsupported) way to get it working now.
