### ISSUE TITLE
SAS Compatibility, Not seeing SAS SMART Status in report

### ISSUE THREAD

**Issue by jshacar** [dak180/FreeNAS-Report#21]
I'm running TrueNAS-13.0-U4 and the latest version of this report (f636c62). In the cfg file I've set includeSAS="true" but when I run the report I do not get a SAS section in the email. I do have SMART short and long tests scheduled under SMART Tests. I've included the output of smartctl commands below. Is there anything I can do to get these drive to show up in the report? Thanks!
 
SAS Drive Make/Model = HGST HUH728060AL4200

[smartctl -AHil.txt](https://github.com/dak180/FreeNAS-Report/files/11322700/smartctl.-AHil.txt)
[smartctl -AHijl.txt](https://github.com/dak180/FreeNAS-Report/files/11322702/smartctl.-AHijl.txt)

**Comment by dak180** [comment]
@jshacar please run the script with the `-d` flag and attach the dump file it emails you.

**Comment by jshacar** [comment]
Sure! Here's the dump file:
[dumpfiles.zip](https://github.com/dak180/FreeNAS-Report/files/11323427/dumpfiles.zip)

**Comment by dak180** [comment]
What is the output of `sysctl -n kern.disks`?

**Comment by jshacar** [comment]
`da2 da5 da11 da1 da6 da9 da10 da8 da3 da7 da4 da0 ada1 ada0 nvd0`

(I have 12 of the SAS disks, 2 SSDs are boot drives, nvd0 is a slog device)

**Comment by dak180** [comment]
@jshacar on line 2111 change `if smartctl -i "/dev/${drive}" | grep -q "SMART support is: Enabled"; then` to `if smartctl -i "/dev/${drive}" | sed -e 's:[[:blank:]]\{1,\}: :g' | grep -q "SMART support is: Enabled"; then` and let me know if that fixes it for you.

**Comment by jshacar** [comment]
Excellent, yes that fixed it for me! They are now showing in the report. The last two columns "Last Test Age (days)" & "Last Test Type" are filled with N/A and N/A: testing not supported but this may be expected.

**Comment by dak180** [comment]
Now that the script is seeing them if you attach another dump file I can see if that can be fixed or not.

**Comment by jshacar** [comment]
Thanks! Here's the second dumpfile:
[dumpfiles.zip](https://github.com/dak180/FreeNAS-Report/files/11324119/dumpfiles.zip)

**Comment by dak180** [comment]
@jshacar unfortunately those drives do not seem to output that information, (at least in a way `smartctl` can read) so not much I can do there.
