### ISSUE TITLE
Add support for NVMe temp warn/crit limits in configuration file

### ISSUE THREAD

**Issue by ghubjules** [dak180/FreeNAS-Report#28]
My report shows a warning with an NVMe temp of 43c.

The NVMe is mounted directly on a supermicro itx board. I haven't found temperature specs for this specific model, but found this blurb from a review site: Using the S.M.A.R.T. temperature sensor we found the Crucial P2 500GB drive had a minimum temperature 0f 31C, an average temperature of 43C and a maximum temperature of 64C inside our test system with the tempered glass panel on.

Suggest adding nvmeTempWarn & nvmeTempCrit to report.cfg (and appropriate functionality to the script) to allow adjusting the warning and critical thresholds.

**Comment by dak180** [comment]
NVMe already uses the separate SSD `ssdTempCrit` and `ssdTempWarn` values; can you describe the use case you have that you need something specific for NVMe separate from SSDs in general?

**Comment by ghubjules** [comment]
My fault! I assumed (incorrectly) that the SSD settings were for SATA ssd's not NVMe. I set my thresholds appropriately in the .cfg file and confirmed the temp warning is gone in the report.


Excellent work on this script, btw! Encapsulating all of the reporting processes into one script that works across scale and core must have been a chore.
