### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mat-bitty** [dak180/FreeNAS-Report#29]
Hello dear developer(s),

I hope that reaching out here ist ok for you - just let me know if not.

I just installed your report script on my TrueNAS System and really like it. As I am not really familliar with coding this type of applications I was wondering if it would be possible to include an overview of the status of the replication tasks in TrueNAS Scale to the report.

Thanks and bests!

**Comment by dak180** [comment]
@mat-bitty This is out of scope for this project for two reasons: the information is not easily available via the command line and this information is available in the web GUI and it is easy to use the GUI to set up email alerts for such things.
