### ISSUE TITLE
Parse error: bad token/bad expression

### ISSUE THREAD

**Issue by m-rm** [dak180/FreeNAS-Report#39]
The script runs fine, but I receive an additional email with errors:

```
Parse error: bad expression
<stdin>:1


Parse error: bad token
<stdin>:1


Parse error: bad token
<stdin>:1


Parse error: bad expression
<stdin>:1


Parse error: bad expression
<stdin>:1


Parse error: bad token
<stdin>:1


Parse error: bad token
<stdin>:1


Parse error: bad expression
<stdin>:1
```

This looks very similar to https://github.com/dak180/FreeNAS-Report/issues/20. I guess that there is a problem parsing the TBW of 2 Patriot SSDs:

![image](https://github.com/user-attachments/assets/7f79304a-f9c3-4cd6-8457-4cef1feea2fe)

**Comment by dak180** [comment]
Please run the script with `-d` and attach the resulting dump file.

**Comment by m-rm** [comment]
Here you go: [dumpfiles.tar.gz](https://github.com/user-attachments/files/17925416/dumpfiles.tar.gz)

**Comment by JoeSchmuck** [comment]
@dak180 
You might want to find a different way to obtain the dump files since they contain the users email address and anyone can view it here.  Just thinking about privacy.

Cheers,
-Joe

**Comment by dak180** [comment]
@m-rm try [eee4048] and let me know if that works.

**Comment by m-rm** [comment]
Yes, it works. Thank you!
